export const CREATE_COUNTERPARTY = "CREATE_COUNTERPARTY";
export const UPDATE_COUNTERPARTY = "UPDATE_COUNTERPARTY";
export const FETCH_COUNTERPARTY  = "FETCH_COUNTERPARTY";
export const DELETE_COUNTERPARTY = "DELETE_COUNTERPARTY";