export const CREATE_SERVICE_TYPE = "CREATE_SERVICE_TYPE";
export const UPDATE_SERVICE_TYPE = "UPDATE_SERVICE_TYPE";
export const FETCH_SERVICE_TYPE  = "FETCH_SERVICE_TYPE";
export const DELETE_SERVICE_TYPE = "DELETE_SERVICE_TYPE";