export const CREATE_EXPENSE_GROUP = "CREATE_EXPENSE_GROUP";
export const UPDATE_EXPENSE_GROUP = "UPDATE_EXPENSE_GROUP";
export const FETCH_EXPENSE_GROUP  = "FETCH_EXPENSE_GROUP";
export const DELETE_EXPENSE_GROUP = "DELETE_EXPENSE_GROUP";