export const CREATE_REFERENCE  = "CREATE_REFERENCE";
export const UPDATE_REFERENCE  = "UPDATE_REFERENCE";
export const FETCH_REFERENCE   = "FETCH_REFERENCE";
export const DELETE_REFERENCE  = "DELETE_REFERENCE";