export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const FETCH_DEPARTMENT  = "FETCH_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";