export const CREATE_PRODUCT_SERVICE = "CREATE_PRODUCT_SERVICE";
export const UPDATE_PRODUCT_SERVICE = "UPDATE_PRODUCT_SERVICE";
export const FETCH_PRODUCT_SERVICE  = "FETCH_PRODUCT_SERVICE";
export const DELETE_PRODUCT_SERVICE = "DELETE_PRODUCT_SERVICE";