export const CREATE_ORDER = "CREATE_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const FETCH_ORDER  = "FETCH_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const SEND_TO_OPERATION = "SEND_TO_OPERATION"