import cuid from "cuid";

export const sampleDataPersonal = [
  {
    id: cuid(),
    soCode: "23",
    snCode: "02",
    registrationNumber: "0045",
    blankNumber: "İDS 000651",
    accreditationNumber: "2",
    certificateIssueDate: "05.01.2018",
    certificateExpirationDate: "05.01.2019",
    certificateExpirationDate: "",
    participantName: "",
    instructorName: "",
    training: "",
    skill: [],
    productCode: "",
    signOfDocument: "",
    note: "",
  },
  {
    id: cuid(),
    soCode: "23",
    snCode: "02",
    registrationNumber: "0045",
    blankNumber: "İDS 000651",
    accreditationNumber: "2",
    certificateIssueDate: "05.01.2018",
    certificateExpirationDate: "05.01.2019",
    certificateExpirationDate: "",
    participantName: "",
    instructorName: "",
    training: "",
    skill: [],
    productCode: "",
    signOfDocument: "",
    note: "",

  },
  {
    id: cuid(),
    soCode: "23",
    snCode: "02",
    registrationNumber: "0045",
    blankNumber: "İDS 000651",
    accreditationNumber: "2",
    certificateIssueDate: "05.01.2018",
    certificateExpirationDate: "05.01.2019",
    certificateExpirationDate: "05.01.2018",
    participantName: "",
    instructorName: "",
    training: "",
    skill: [],
    productCode: "",
    signOfDocument: "",
    note: "",

  },
];
