import cuid from "cuid";

export const sampleData = [
 
  {
    id: cuid(),
    firstname: "Elshan",
    lastname: "Zairov",
    middlename: "Bərəhman",
    birthday: "15.05.1997",
    place: "A.Qərib",
    phone: "50 500 11 49",

    website: "zairov.com",
    whatsapp: "zairov.e",
    telegram: "zairov",
    facebook: "",
    linkedin: "https://www.linkedin.com/in/elshan-zairov/",
    twitter: "",
    instagram: "",
    mail: "nuvedili@gmail.com",

    duty: "developer",
    department: "",
    startWork: "01.01.2017",
    circulation: "1600",
    bonus: "",
    customerSatisfaction: "",
    performance: 50,
  },
  {
    id: cuid(),
    firstname: "Qadir",
    lastname: "Novruzov",
    middlename: "Bərəhman",
    birthday: "15.05.1997",
    place: "A.Qərib",
    phone: "50 500 11 49",

    website: "zairov.com",
    whatsapp: "zairov.e",
    telegram: "zairov",
    facebook: "",
    linkedin: "https://www.linkedin.com/in/elshan-zairov/",
    twitter: "",
    instagram: "",
    mail: "nuvedili@gmail.com",

    duty: "developer",
    department: "",
    startWork: "01.01.2017",
    circulation: "1600",
    bonus: "",
    customerSatisfaction: "",
    performance: 30,
  },
  {
    id: cuid(),
    firstname: "Hesen",
    lastname: "Suleymanli",
    middlename: "Bərəhman",
    birthday: "15.05.1997",
    place: "A.Qərib",
    phone: "50 500 11 49",

    website: "zairov.com",
    whatsapp: "zairov.e",
    telegram: "zairov",
    facebook: "",
    linkedin: "https://www.linkedin.com/in/elshan-zairov/",
    twitter: "",
    instagram: "",
    mail: "nuvedili@gmail.com",

    duty: "developer",
    department: "",
    startWork: "01.01.2017",
    circulation: "1600",
    bonus: "",
    customerSatisfaction: "",
    performance: 20,
  },

];
