import cuid from "cuid";

export const sampleDataCrm = [
 
  {
    id: cuid(),

    firstname: "",
    lastname: "",
    middlename: "",
    birthday: "",
    p_phone:"",
    p_whatsapp: "",
    p_telegram: "",
    p_facebook: "",
    p_linkedin: "",
    p_twitter: "",
    p_instagram: "",
    p_mail: "",

    curator: "Elshan",
    customerCode: "Zairov66",
    customerName: "Bərəhman",
    vöen: "A55sdA",
    createDate: "17/04/2020",

    logo:"",
    place:"A.Qerib kuc",
    phone:"0505001149",
    website: "zairov.com",
    whatsapp: "zairov.e",
    telegram: "zairov",
    facebook: "",
    linkedin: "https://www.linkedin.com/in/elshan-zairov/",
    twitter: "",
    instagram: "",
    mail: "nuvedili@gmail.com",

    reference: "Elshan",
    circulation: "1600",
    customerCategory:"",
    customerSatisfaction: "",
    note: "50 500 11 49",

  },
  {
    id: cuid(),

    firstname: "",
    lastname: "",
    middlename: "",
    birthday: "",
    p_phone:"",
    p_whatsapp: "",
    p_telegram: "",
    p_facebook: "",
    p_linkedin: "",
    p_twitter: "",
    p_instagram: "",
    p_mail: "",


    curator: "Elshan",
    customerCode: "Zairov66",
    customerName: "Bərəhman",
    vöen: "A55sdA",
    createDate: "17/04/2020",

    logo:"",
    place:"A.Qerib kuc",
    phone:"0505001149",
    website: "zairov.com",
    whatsapp: "zairov.e",
    telegram: "zairov",
    facebook: "",
    linkedin: "https://www.linkedin.com/in/elshan-zairov/",
    twitter: "",
    instagram: "",
    mail: "nuvedili@gmail.com",

    reference: "Elshan",
    circulation: "1600",
    customerCategory:"",
    customerSatisfaction: "",
    note: "50 500 11 49",
  },
  {
    id: cuid(),

    firstname: "",
    lastname: "",
    middlename: "",
    birthday: "",
    p_phone:"",
    p_whatsapp: "",
    p_telegram: "",
    p_facebook: "",
    p_linkedin: "",
    p_twitter: "",
    p_instagram: "",
    p_mail: "",
    
    curator: "Elshan",
    customerCode: "Zairov66",
    customerName: "Bərəhman",
    vöen: "A55sdA",
    createDate: "17/04/2020",

    logo:"",
    place:"A.Qerib kuc",
    phone:"0505001149",
    website: "zairov.com",
    whatsapp: "zairov.e",
    telegram: "zairov",
    facebook: "",
    linkedin: "https://www.linkedin.com/in/elshan-zairov/",
    twitter: "",
    instagram: "",
    mail: "nuvedili@gmail.com",

    reference: "Elshan",
    circulation: "1600",
    customerCategory:"",
    customerSatisfaction: "",
    note: "50 500 11 49",
  },

];
