import cuid from "cuid";

export const sampleDataControlSystem = [
  {
    id: cuid(),
    soCode: "23",
    snCode: "02",
    registrationNumber: "0045",
    blankNumber: "İDS 000651",
    accreditationNumber: "2",
    certificateIssueDate: "05.01.2018",
    certificateExpirationDate: "05.01.2019",
    businessEntityName: "Dji i Rus İnfra MMC",
    legalStatus: "Hüquqi şəxs",
    VOEN: "5077746899687",
    economicEntityPhoneNumber: "84957396811",
    legalAddressOfTheBusinessEntity: "Rusiya Federasiyası,Moskva şəhəri,Peresnenkaya Naberejnaya ev 10",
    actualAddressOfTheBusiness: "Rusiya Federasiyası,Moskva şəhəri,Peresnenkaya Naberejnaya ev 10",
    nameOfTheProduct: "Portativ vibroanalizatorlar Scout 100-Ex",
    quantity: "30",
    productNote: "Qeyri-ərzaq",
    productCode: "26.30",
    countryOfOrigin: "US",
    signOfLegalAct: "Directive 2014/34/EU, EN 60079-0:2012/A11:2013, EN 60079-11:2012, İEC 62133:2002",
    certificateIsRecognized: "US",
    recognitionProcessNote: "Aparılmayıb",
    accreditedLaboratoryName: "",
    accreditedLaboratoryNumber: "",
    testQuantity: "",
    productBatchHistory: "",
    note:""
  },
  {
    id: cuid(),
    soCode: "23",
    snCode: "02",
    registrationNumber: "0045",
    blankNumber: "İDS 000651",
    accreditationNumber: "2",
    certificateIssueDate: "05.01.2018",
    certificateExpirationDate: "05.01.2019",
    businessEntityName: "Dji i Rus İnfra MMC",
    legalStatus: "Hüquqi şəxs",
    VOEN: "5077746899687",
    economicEntityPhoneNumber: "84957396811",
    legalAddressOfTheBusinessEntity: "Rusiya Federasiyası,Moskva şəhəri,Peresnenkaya Naberejnaya ev 10",
    actualAddressOfTheBusiness: "Rusiya Federasiyası,Moskva şəhəri,Peresnenkaya Naberejnaya ev 10",
    nameOfTheProduct: "Portativ vibroanalizatorlar Scout 100-Ex",
    quantity: "30",
    productNote: "Qeyri-ərzaq",
    productCode: "26.30",
    countryOfOrigin: "US",
    signOfLegalAct: "Directive 2014/34/EU, EN 60079-0:2012/A11:2013, EN 60079-11:2012, İEC 62133:2002",
    certificateIsRecognized: "US",
    recognitionProcessNote: "Aparılmayıb",
    accreditedLaboratoryName: "",
    accreditedLaboratoryNumber: "",
    testQuantity: "",
    productBatchHistory: "",
    note:""


  },
  {
    id: cuid(),
    soCode: "23",
    snCode: "02",
    registrationNumber: "0045",
    blankNumber: "İDS 000651",
    accreditationNumber: "2",
    certificateIssueDate: "05.01.2018",
    certificateExpirationDate: "05.01.2019",
    businessEntityName: "Dji i Rus İnfra MMC",
    legalStatus: "Hüquqi şəxs",
    VOEN: "5077746899687",
    economicEntityPhoneNumber: "84957396811",
    legalAddressOfTheBusinessEntity: "Rusiya Federasiyası,Moskva şəhəri,Peresnenkaya Naberejnaya ev 10",
    actualAddressOfTheBusiness: "Rusiya Federasiyası,Moskva şəhəri,Peresnenkaya Naberejnaya ev 10",
    nameOfTheProduct: "Portativ vibroanalizatorlar Scout 100-Ex",
    quantity: "30",
    productNote: "Qeyri-ərzaq",
    productCode: "26.30",
    countryOfOrigin: "US",
    signOfLegalAct: "Directive 2014/34/EU, EN 60079-0:2012/A11:2013, EN 60079-11:2012, İEC 62133:2002",
    certificateIsRecognized: "US",
    recognitionProcessNote: "Aparılmayıb",
    accreditedLaboratoryName: "",
    accreditedLaboratoryNumber: "",
    testQuantity: "",
    productBatchHistory: "",
    note:""

  },
];
