export const CREATE_EMPLOYEES = "CREATE_EMPLOYEES";
export const UPDATE_EMPLOYEES = "UPDATE_EMPLOYEES";
export const FETCH_EMPLOYEES  = "FETCH_EMPLOYEES";
export const DELETE_EMPLOYEES = "DELETE_EMPLOYEES";