export const CREATE_ORDER_SOURCE  = "CREATE_ORDER_SOURCE";
export const UPDATE_ORDER_SOURCE  = "UPDATE_ORDER_SOURCE";
export const FETCH_ORDER_SOURCE   = "FETCH_ORDER_SOURCE";
export const DELETE_ORDER_SOURCE  = "DELETE_ORDER_SOURCE";