export const CREATE_OPERATION = "CREATE_OPERATION";
export const UPDATE_OPERATION = "UPDATE_OPERATION";
export const FETCH_OPERATION  = "FETCH_OPERATION";
export const DELETE_OPERATION = "DELETE_OPERATION";