export const CREATE_CONTROL_SYSTEM = "CREATE_CONTROL_SYSTEM";
export const UPDATE_CONTROL_SYSTEM = "UPDATE_CONTROL_SYSTEM";
export const FETCH_CONTROL_SYSTEM  = "FETCH_CONTROL_SYSTEM";
export const DELETE_CONTROL_SYSTEM = "DELETE_CONTROL_SYSTEM";