export const CREATE_DOCUMENTTYPE = "CREATE_DOCUMENTTYPE";
export const UPDATE_DOCUMENTTYPE = "UPDATE_DOCUMENTTYPE";
export const FETCH_DOCUMENTTYPE  = "FETCH_DOCUMENTTYPE";
export const DELETE_DOCUMENTTYPE = "DELETE_DOCUMENTTYPE";