export const CREATE_SIGN_OF_LEGAL_ACT = "CREATE_SIGN_OF_LEGAL_ACT";
export const UPDATE_SIGN_OF_LEGAL_ACT = "UPDATE_SIGN_OF_LEGAL_ACT";
export const FETCH_SIGN_OF_LEGAL_ACT  = "FETCH_SIGN_OF_LEGAL_ACT";
export const DELETE_SIGN_OF_LEGAL_ACT = "DELETE_SIGN_OF_LEGAL_ACT";