export const CREATE_EXPENSE_TYPE = "CREATE_EXPENSE_TYPE";
export const UPDATE_EXPENSE_TYPE = "UPDATE_EXPENSE_TYPE";
export const FETCH_EXPENSE_TYPE  = "FETCH_EXPENSE_TYPE";
export const DELETE_EXPENSE_TYPE = "DELETE_EXPENSE_TYPE";